packageExtensions:
  '@tensorflow-models/posenet@*':
    dependencies:
      '@tensorflow/tfjs-core': '*'
      '@tensorflow/tfjs-converter': '*'
  '@tensorflow/tfjs-data@*':
    dependencies:
      '@tensorflow/tfjs-core': '*'
      'seedrandom': '*'