packageExtensions:
  '@tensorflow/tfjs-data@*':
    dependencies:
      '@tensorflow/tfjs-core': '*'
      'seedrandom': '*'
  '@tensorflow-models/pose-detection@*':
    dependencies:
      '@mediapipe/pose': '*'
      '@tensorflow/tfjs-core': '*'
      '@tensorflow/tfjs-converter': '*'
      '@tensorflow/tfjs-backend-wasm': '*'
  '@tensorflow/tfjs-backend-webgl@*':
    dependencies:
      '@tensorflow/tfjs-core': '*'
  '@tensorflow/tfjs-backend-webgpu@*':
    dependencies:
      '@tensorflow/tfjs-core': '*'
  '@tensorflow/tfjs-backend-cpu@*':
    dependencies:
      '@tensorflow/tfjs-core': '*'
  '@tensorflow/tfjs-converter@*':
    dependencies:
      '@tensorflow/tfjs-core': '*'